### ISSUE TITLE
Cannot find module 'sunbird'.

### ISSUE THREAD

**Issue by yogesh-sinoriya** [Sunbird-Ed/SunbirdEd-mobile#96]
Hello Team, I am trying to start the ionic mobile app. But while starting is giving an error 
**Typescript Error
Cannot find module 'sunbird'.**

Please let me know where I can find the sunbird module.

**Comment by souvikmondal** [comment]
please follow updated readme

**Comment by yogesh-sinoriya** [comment]
Thanks, Team
It's resolved my sunbird dependencies, But I am still facing some issue while with sunbird methods, 
I am getting many errors like. 
```
typescript: src/pages/profile/profile.ts, line: 560
             Expected 6 arguments, but got 4.
560:      this.contentService.searchContent(req,
```

Our server is working with sunbird v1.6, So please guide me which branch or tag I should prefer.
If you give a complete set of instruction, To build ionic mobile. Then it's really appreciated.

**Comment by swayangjit** [comment]
are you taking the code from release-1.6.0 if yes then you have to add all the plugins from the same branch release-1.6.0

or else you can run ./build.sh <branch_name>
